### PR TITLE
Change location of docker images.

### PR DESCRIPTION
**Pull request by hacktobeer**
Change the location of the docker images to pull from the Artifact Registry of the osdfir-registry project.

### CODE REVIEW

**Comment by hacktobeer** [comment]
Hold for now as build fail due to GCP library conflicts.

**Comment by aarontp** [comment]
We also need to migrate over the other build triggers before we commit this.

**Comment by aarontp** [comment]
Also, there are some overrides set in deploy.sh that will need to be updated.  In theory we could submit this as is without updating those or copying over the new build triggers, but we should probably do both at once so we're not using two different repos.

**Comment by hacktobeer** [comment]
Agree, I'll happily migrate all triggers if I can access the current project.

**Comment by hacktobeer** [comment]
Triggers have been migrated to new project and all images have been (manually build).

**Review by berggren — APPROVED** [review]

**Pull request merged**
