### PR TITLE
Migrate container definition to terraform and add data volume

### PR DESCRIPTION
**Pull request by aarontp**
* Migrates inline text based container config to Terraform modules
* Adds and attaches new volume disks for Turbinia output
* Creates new variables for Turbinia output directories so Docker startup script can create directories

### CODE REVIEW

**Comment by aarontp** [comment]
This is the current error:
```
Error: Failed to start container: Volume data-disk-0: Could not determine if the GCE Persistent Disk turbinia-worker-ea75a2366e88f51a-0-data-disk is attached read-only or read-write.
```

And this is where it's failing in the konlet code that sets up the container:
https://github.com/GoogleCloudPlatform/konlet/blob/14a1d0ddaba145b46e19c1ee02c53cf983180585/gce-containers-startup/volumes/volumes.go#L322

**Comment by aarontp** [comment]
The disk appears to be listed in the metadata, but possibly named incorrectly.  Following the konlet code from https://github.com/GoogleCloudPlatform/konlet/blob/master/gce-containers-startup/metadata/provider.go, I can recreate the check with curl, and the device name appears different from what it shows in the logs:

```
curl "http://metadata.google.internal/computeMetadata/v1/instance/disks/?recursive=true" -H "Metadata-Flavor: Google"
[{"deviceName":"persistent-disk-0","index":0,"interface":"SCSI","mode":"READ_WRITE","type":"PERSISTENT"},{"deviceName":"data-disk-0","index":1,"interface":"SCSI","mode"
:"READ_WRITE","type":"PERSISTENT"}
```

**Comment by aarontp** [comment]
Ok, this is now working (along with some minor changes to the Docker startup script: https://github.com/google/turbinia/pull/655).

**Comment by hacktobeer** [comment]
```
ramsesdebeer@cloudshell:~/osdfir-infrastructure (ramses-test5)$ terraform validate
Error: Reserved argument name in module block
  on modules/turbinia/main.tf line 336, in module "gce-worker-container":
 336:   count  = var.turbinia_worker_count
The name "count" is reserved for use in a future version of Terraform.
```

**Comment by aarontp** [comment]
Yeah, that's strange, I guess it must be something version dependent. 
```
$ ~/bin/terraform --version

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.47.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

$ ~/bin/terraform validate
Success! The configuration is valid.
```

@berggren Any thoughts?

**Comment by hacktobeer** [comment]
So you use a *newer* version compared to mine and you do not get an error message.....that is indeed weird (and maybe not unexpected from Terraform.....ugh).

**Comment by aarontp** [comment]
LMK if this is good after https://github.com/google/turbinia/pull/657

**Comment by hacktobeer** [comment]
With the new Terraform this works, all good.

**Review by hacktobeer — APPROVED** [review]

**Comment by aarontp** [comment]
Cool, @berggren Did you want to review this as well?  Or is it good to merge?

**Review by berggren — APPROVED** [review]
LGTM

**Pull request merged**
