### PR TITLE
Bind /var/lib/turbinia to host

### PR DESCRIPTION
**Pull request by aarontp**
This is an attempt to fix https://github.com/google/turbinia/issues/645 .

### CODE REVIEW

**Comment by aarontp** [comment]
@hacktobeer : This seems to successfully mount/bind the directory to the host (so that we don't fill up the containers with output), but the process still can't write to the container and gets errors.  The directory is chown'd to the correct user within the container, but the directory is owned by root in the host filesystem.  I'm not sure how users are supposed to be mapped between the two systems.  Any ideas how to resolve this? 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819-py3.6.egg/turbinia/client.py", line 234, in check_directory
    os.chmod(directory, mode | stat.S_IWUSR)
PermissionError: [Errno 1] Operation not permitted: '/var/lib/turbinia'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/turbiniactl", line 33, in <module>
    sys.exit(load_entry_point('turbinia==20190819', 'console_scripts', 'turbiniactl')())
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819-py3.6.egg/turbinia/turbiniactl.py", line 634, in main
    jobs_denylist=args.jobs_denylist, jobs_allowlist=args.jobs_allowlist)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819-py3.6.egg/turbinia/client.py", line 1240, in __init__
    check_directory(config.OUTPUT_DIR)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819-py3.6.egg/turbinia/client.py", line 237, in check_directory
    'Can not add write permissions to {0:s}'.format(directory))
turbinia.TurbiniaException: Can not add write permissions to /var/lib/turbinia
```

**Comment by hacktobeer** [comment]
You are mounting the container host folder /var/lib/turbinia to the container folder /var/lib/turbinia. I suspect the host filesystem has permissions set that the turbinia user in the container is unable to write to. Two options here, we try to debug how users are mapped and rely on that *or* we mount a separate data disk to the container host and map that into the container so we don't touch the actual container host filesystem. This will give us a clear seperation between the turbinia worker/server data and the container (host) is data.

**Comment by aarontp** [comment]
I'll try to take a look at how the user mappings are done.  Yeah, a separate data disk might be a good idea though.

**Comment by aarontp** [comment]
Dropping this PR since I think adding the volume is the right approach here (https://github.com/forseti-security/osdfir-infrastructure/pull/17/ for that).

**Pull request closed without merging**
